### ISSUE TITLE
Directives not displayed in UI

### ISSUE THREAD

**Issue by khalil-omer** [apollographql/embeddable-explorer#10]
(If this is the wrong repo, please let me know)

- Add a standard directive like @deprecated to an operation in your schema -> Explorer will display that directive in the schema docs located at https://studio.apollographql.com/sandbox/schema 

- Now add a custom directive like @auth to your schema --> Explorer doesn't seem to recognize this at all. 

**Is this intentional behavior? Feels like a bug,**

Thanks!

**Comment by shellscape** [comment]
@mayakoneval is there anyone from Apollo looking at issues here? This and others are crickets.

**Comment by mayakoneval** [comment]
Hi! this is the wrong repo, that would be an issue for https://github.com/apollographql/apollo-studio-community. Apologies for the late reply

**Comment by shellscape** [comment]
@mayakoneval we have the ability to transfer issues rather than closing them now...
