### ISSUE TITLE
Displaying the SDL

### ISSUE THREAD

**Issue by shellscape** [apollographql/embeddable-explorer#117]
Are there any plans to allow showing the SDL within the embeddable explorer, similar to https://studio.apollographql.com/sandbox/schema/sdl ?

If not, any key pointers for users wishing to roll their own display of the SDL?

**Comment by cheapsteak** [comment]
We're presently aiming to have embedded Explorer remain just the Explorer query builder, although you can now also embed Sandbox as well if you wish  

Are you using Apollo Server?  
The easiest way to do that would be to install the apollo-server 3.8.1 and configure the constructor to include the plugin `ApolloServerPluginLandingPageLocalDefault({ embed: true })`

You can also reference the code there to see how to embed Sandbox
https://github.com/mayakoneval/apollo-server/blob/fa0970f21b4dfb854190f7c786650c019e86c9df/packages/apollo-server-core/src/plugin/landingPage/default/index.ts#L125-L145

**Comment by shellscape** [comment]
> Are you using Apollo Server?

In some scenarios, yes. In our primary use, no. We're tacking this onto a Postgraphile implementation. I'll take a look at the code you linked to and will report back. Thanks for the pointer.

**Comment by daniman** [comment]
@shellscape we have a way to embed the whole Sandbox now — maybe that’s what you’re looking for? https://www.apollographql.com/docs/studio/explorer/sandbox/#embedding-sandbox

**Comment by shellscape** [comment]
cool, I'll check this out later today. when we implemented the embeddable explorer, this was not yet available.

**Comment by shellscape** [comment]
So while the embeddable sandbox is nice, it's not open source and the available configuration is a fraction of the embeddable explorer. The embeddable sandbox is just a thin wrapper around this url https://github.com/apollographql/embeddable-explorer/blob/bab56815905f855468772671cf092119c8734eb2/src/helpers/constants.ts#L4

The old playground and GraphiQL are both open source, but inferior experiences imho. So it was very cool to see the explorer open sourced and available. Given that playground pretty effortlessly displayed the SDL, I was hoping that it would be possible with the explorer without using a closed-source script.

**Comment by cheapsteak** [comment]
Ah, both embeddable explorer and embeddable sandbox are actually only open-sourced in their wrappers. The source for both is pretty tied into studio's saas codebase and we don't currently have it on our roadmap to extricate that 

But if you'd wish to roll your own display of SDL it should be pretty straightforward :)  

- introspect the endpoint to get the introspection schema with `getIntrospectionQuery`
- convert that into an executable schema with `buildClientSchema`
- print that schema into SDL via `printSchema`

More on graphql schema conversions [here](https://www.apollographql.com/blog/backend/schema-design/three-ways-to-represent-your-graphql-schema/), specifically "Introspection query result to SDL"

**Comment by shellscape** [comment]
We're already providing the schema as a string to the initialization function for the explorer, so we've already got that SDL available. (It's something that postgraphile outputs to file).

I wasn't actually aware that the explorer was also a wrapper around `EMBEDDABLE_EXPLORER_URL`. (This isn't something I had setup, just took over ownership.) If Apollo is producing a UMD bundle for this, certainly the relevant parts that enable to bundle could be open sourced. I'm pretty disappointed that it's not, will definitely be re-evaluating going back to the old playground. Appreciate the info at any rate.

As a suggestion, in lieu of opening the source for either, there's a vast gulf between the available options for explorer and those available for the embedded sandbox. And it's worth restating that the docs for the embeddable sandbox need love, and are non-existent within this repo.

**Comment by cheapsteak** [comment]
The UMD is part of this repo, but Explorer itself is exposed via an embedded iframe (network requests are postMessaged out to the parent embedding page)

And much appreciate the suggestion 🙏 Out of curiosity, which config options would be of particular interest for you for embedded sandbox?

**Comment by shellscape** [comment]
@mayakoneval how was this completed?

**Comment by cheapsteak** [comment]
I believe the request to embed this other view outside of explorer would be out of scope for the embedded explorer repo

**Comment by cheapsteak** [comment]
that SDL view _is_ available if you'd like to embed Sandbox 
https://github.com/apollographql/embeddable-explorer/tree/main/packages/sandbox
