### ISSUE TITLE
Custom theming explorer

### ISSUE THREAD

**Issue by shabab477** [apollographql/embeddable-explorer#156]
Hello,

I am looking to use the embedded explorer as part but couldn't find any documentation related to theming the explorer UI. Also I was looking for the ability to remove the login button and the ability to change logo from the explorer. 

Is it possible to do these things as of right now? or if you are open to implement these in the future, then I can help.

**Comment by mayakoneval** [comment]
Hi, you can set the theme of the explorer to dark or light with the `theme` option in the config, but we don't support changing the logo at the moment 🙏🏻
