### ISSUE TITLE
Sandbox explorer passes cookies locally when includeCookies is set to false

### ISSUE THREAD

**Issue by bigman73** [apollographql/embeddable-explorer#176]
## Description
Apollo Server v4's sandbox explorer landing page has a property named `includeCookies`.
The property is documented to default to `false`.
https://github.com/apollographql/apollo-server/blob/6808c3b960cac09d759ba6f3c9b3e22fcda2d286/docs/source/api/plugin/landing-pages.mdx#includecookies

However, when executing a query in the explorer against a local service the cookies are passed to the resolvers.

## Version
@apollo/server: 4.0.2

## Version of Apollo Server that didn't happen
apollo-server-core: 3.10.3
apollo-server-express": 3.10.3

## Expected behavior
When `includeCookies` is set to false (the default) no cookies should be passed to the resolvers, in any scenario, including a local service

## Actual behavior
Cookies are passed to the resolvers in local service mode
It's a breaking change compared to Apollo Server v3

## Reproducing
1. Use any hello world Apollo Server V4 example as described in the Apollo Server documentation
2. Open the sandbox explorer on a local machine 
3. Open the browser's network diagnostics tab
4. Execute a basic GraphQL query, such as heartbeat
5. Examine the outgoing HTTP request in networking - the cookies are sent with the request

## More information
The problem may be coming from this line:
https://github.com/apollographql/embeddable-explorer/blob/9893948e8b459169e912dd18790dfe247bee29f6/packages/explorer/src/helpers/defaultHandleRequest.ts#L11

When `includeCookies` is `false` then the `fetch` credentials option is set to {} (empty object).
`fetch` defaults in that case to `same-origin` and therefore sends the cookies locally since they are the same origin. The correct value should be set explicitly to `omit`.

https://developer.mozilla.org/en-US/docs/Web/API/fetch

**Comment by mayakoneval** [comment]
Hi! Thanks for raising this, I have merged your PR with some docs changes & this should be updated in the next major version of each package by end of day 🙏
