### ISSUE TITLE
Allow setting shouldAutoUpdateSchema to false 

### ISSUE THREAD

**Issue by brentleeper** [apollographql/embeddable-explorer#185]
-Allow passing an argument to the constructor of EmbeddedSandbox to set shouldAutoUpdateSchema: false
-Listen for an event which will allow the user to update the value of shouldAutoUpdateSchema

**Comment by brentleeper** [comment]
I want to set the initial state so that schema polling is turned off on a client's first load. I would be even better if I could completely disable the option.

**Comment by brentleeper** [comment]
Does anyone maintain this repo?

**Comment by henning-kvinnesland** [comment]
Code below isn't pretty, but probably does what you are after. Runs inspection query only once.

```js

let introspectionResponse: Response;

const isIntrospectionQuery = (options: Omit<RequestInit, 'headers'>) => {
    const { body } = options;

    if (typeof body !== 'string') {
        return;
    }

    const requestBody = JSON.parse(body);
    const { operationName } = requestBody;

    return operationName === 'IntrospectionQuery';
};

const handleRequest: HandleRequest = async (endpointUrl, options) => {
    const queryIsIntrospection = isIntrospectionQuery(options);

    if (queryIsIntrospection && introspectionResponse) {
        return introspectionResponse.clone();
    }

    const response = await fetch(endpointUrl, {
        ...options,
        headers: {
            ...options.headers,
            token: await getToken(),
            project,
            username: getUsername()
        }
    });

    if (queryIsIntrospection) {
        introspectionResponse = response.clone();
    }

    return response;
};

```

**Comment by brentleeper** [comment]
That is a nice little work around. I basically ended up doing this on the backend. Only actually run the introspection once after server start up and saving the response to return on each subsequent introspection request.

**Comment by henning-kvinnesland** [comment]
I just wanted the network-panel in Chrome to be cleaner. :)

**Comment by ck-developer** [comment]
+1

**Comment by mayakoneval** [comment]
Hey folks, this is out in 3.1.0 with `pollForSchemaUpdates` [as an `initialState` config option](https://www.apollographql.com/docs/graphos/explorer/sandbox/#pollforschemaupdates). Thanks for the report!

**Comment by brentleeper** [comment]
🙌🙌 Thank you!
