### ISSUE TITLE
is it possible to send a query to edit and run in the embedded sandbox?

### ISSUE THREAD

**Issue by KeithKelleher** [apollographql/embeddable-explorer#213]
The current version of our site had an API page where users could start with different queries to edit in the playground. This was done by setting the playground's iframe to the url+"?query=blahblahblah" when the user wanted to run a specific query.

See: https://pharos.nih.gov/api

Upgrading to the embedded apollo sandbox it doesn't seem like I can do that anymore. I can set an initialState, but it only works if the user has never used the sandbox before, because the initialState I set seems to get overwritten by the user's previous query.

I'd like to be able to send a new query to the sandbox that the user can edit and run. Is there a way to do that?

**Comment by mayakoneval** [comment]
Hi @KeithKelleher if you add `?document=blahblahblah` to the url you sent me like `https://pharos.nih.gov/api?document=blahblahblah` it will populate in the Sandbox Explorer

**Comment by KeithKelleher** [comment]
This is great. Just what I needed. Cheers.
