### ISSUE TITLE
ApolloServerPluginLandingPageLocalDefault: headers not passed to IntrospectionQuery

### ISSUE THREAD

**Issue by jlowcs** [apollographql/embeddable-explorer#214]
### Issue Description

When using `ApolloServerPluginLandingPageLocalDefault`, the `headers` option is used for every graphql query, except for the `IntrospectionQuery` one, which is an issue in our case because we are expecting a specific custom header for all our graphql queries.

This used to work with Apollo Server v3.

### Link to Reproduction

N/A

### Reproduction Steps

1. add the plugin:
```js
ApolloServerPluginLandingPageLocalDefault({
  headers: {
    'x-custom': 'foobar',
  },
})
```
2. Open the playground, check the devtools for the first graphql request
=> the 'x-custom' header is missing

**Comment by mayakoneval** [comment]
Hello, thank you for the report.

The `headers` option in `ApolloServerPluginLandingPageLocalDefault` populates the initial tab headers on first load of Sandbox. Introspection requests in Sandbox take headers from the Shared Headers, which you can find in the Connection Settings by navigating to the Explorer page -> Settings tab in the left pane -> clicking the 'Edit' button as in the image below.

<img width="603" alt="Screen Shot 2023-01-24 at 10 49 23 AM" src="https://user-images.githubusercontent.com/14367451/214382063-1e24b1c9-34a5-4d9d-a717-96df79d93599.png">

There is currently no way to set these Shared Headers from the embedded Sandbox config for everyone using the Sandbox, so I have added a ticket to our board for adding a config option for these headers in particular.

Thanks again, I'll keep you updated.

**Comment by mayakoneval** [comment]
Hi, apologies for the delay. I forgot to update here. With the latest[ @apollo/server ](https://www.npmjs.com/package/@apollo/server)release, you can now pass `sharedHeaders` to your Sandbox, and these will be applied to your introspection queries. 

See details in the docs [here](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/#sharedheaders)

Thanks!

**Comment by jlowcs** [comment]
There seems to be an introspection query being sent without the `sharedHeaders` in the latest version, although it is followed by another introspection query that contains the headers. Is that on purpose?
