### ISSUE TITLE
Shared Headers fields are broken

### ISSUE THREAD

**Issue by Arrivegrsmith** [apollographql/embeddable-explorer#251]
Unable to add headers to explorer/sandbox configuration. Issue exists in incognito mode and no plugins enabled.

Browser: Firefox 112.0.1
OS: MacOS Ventura 13.2.1

<img width="753" alt="Screenshot 2023-04-20 at 1 59 46 PM" src="https://user-images.githubusercontent.com/105511290/233462462-96fda888-f955-41a9-80bc-48f2be2635ea.png">

**Comment by Arrivegrsmith** [comment]
Similar issue reported also on SO https://stackoverflow.com/questions/75981765/why-are-shared-headers-disabled-in-apollo-sandbox

**Comment by Arrivegrsmith** [comment]
Issue was not present on Apr 12th 2023.

**Comment by Az-r-ow** [comment]
There is no documented way of enabling setting shared headers from withing the sandbox. However, you can pass your shared headers when initializing the Apollo Server landing page this way : 

```js
const landingPagePlugin = ApolloServerPluginLandingPageLocalDefault({
       embed: {
         initialState: {
           sharedHeaders: {
             foo: 'foo',
           },
         },
       },
    })

const apolloServer = new ApolloServer({
  schema,
  plugins: [landingPagePlugin]
})
```

And you should see your shared headers in the sandbox : 

![Screenshot from 2023-04-21 14-54-59](https://user-images.githubusercontent.com/74182707/233641396-5fa87dae-17cc-4468-a24c-fcae2575eb55.png)

> Ref : https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/#initialstate-options

**Comment by Arrivegrsmith** [comment]
To clarify: those fields used to be user editable.
<img width="537" alt="Screenshot 2023-04-21 at 9 39 24 AM" src="https://user-images.githubusercontent.com/105511290/233664412-eae8cc84-811d-43aa-9bdc-08b4941c9478.png">

**Comment by BaptisteMartinet** [comment]
Same issue here. Text inputs are disabled in the DOM.
Only solution is to inspect them and remove the "disabled" attribute.

**Comment by mayakoneval** [comment]
hi! You can actually pass your shared headers in Sandbox via `initialState.sharedHeaders`. I'll add this to the documentation, thanks for calling it out. 

The disabled input was a bug that should be fixed now, can you confirm? Thanks!

**Comment by BaptisteMartinet** [comment]
> hi! You can actually pass your shared headers in Sandbox via `initialState.sharedHeaders`. This is documented here https://www.apollographql.com/docs/graphos/explorer/sandbox/#sharedheaders
> 
> The disabled input was a bug that should be fixed now, can you confirm? Thanks!

I confirm that it's working again on my side. Thanks for your service!
