### ISSUE TITLE
Hiding the gql response tab

### ISSUE THREAD

**Issue by wcardosodev** [apollographql/embeddable-explorer#259]
Hi there,

Do you have any plans for being able to hide the response tab in the explorer or even just having it "closed" similar to how you can set a displayOption for `docsPanelState: 'closed' | 'open'`? 

Our use case is that we want to be able to query via the graphql embedded component but then we handle rendering that data ourselves rather than showing it in the explorer

**Comment by mayakoneval** [comment]
Hi there, we don't have this planned at the moment, but we can track that you requested it. Thanks!
