### ISSUE TITLE
Still seeing stripe requests, sentry logs with `runTelemetry: false`

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/embeddable-explorer#266]
I can make an actual repo if the zip file doesn't work. CodeSandbox isn't a good repro for this because of all the extra noise in the network tab.

```
npm i && npm start
```
Open network tab, observe request to stripe

<img width="927" alt="image" src="https://github.com/apollographql/embeddable-explorer/assets/29644393/3d59d21c-1ef4-4aa9-b2f5-bc2d7ea225eb">

[server-typescript-1689955125468.zip](https://github.com/apollographql/embeddable-explorer/files/12130525/server-typescript-1689955125468.zip)

Reported here: https://github.com/apollographql/apollo-server/issues/7623

**Comment by aclarknexient** [comment]
I'm very glad that this will be worked on. Our corporate cybersecurity department has banned development tools that make unwanted external network requests!

**Comment by mayakoneval** [comment]
Hi thanks for the report! We have a fix in progress for this. I will update asap.

**Comment by mayakoneval** [comment]
Hi! I forgot to update on this, but we should have fixed this on Aug 8. Closing

**Comment by aclarknexient** [comment]
@mayakoneval unfortunately we are still seeing the calls to stripe and others. This was in a clean install with apolloserver 4.9.4.

The code used was:

```javascript
import { ApolloServerPluginDrainHttpServer } from '@apollo/server/plugin/drainHttpServer';
import { ApolloServerPluginLandingPageLocalDefault, ApolloServerPluginLandingPageProductionDefault } from '@apollo/server/plugin/landingPage/default';

const server = new ApolloServer({
  schema,
  introspection: true,
  plugins: [ApolloServerPluginDrainHttpServer({ httpServer })],
  allowBatchedHttpRequests: true,
  plugins: [
    process.env.NODE_ENV === 'production'
      ? ApolloServerPluginLandingPageProductionDefault({
        embed: {
          runTelemetry: false
        }
      })
      : ApolloServerPluginLandingPageLocalDefault({
        embed: {
          runTelemetry: false
        }
      }),
  ]
});
```

**Comment by mayakoneval** [comment]
replied over here ! https://github.com/apollographql/embeddable-explorer/issues/285 

Thanks as always!

**Comment by advance512** [comment]
Unfortunately we still see this happening with apollo/server v4.12.0.

![Image](https://github.com/user-attachments/assets/6b6abc11-92bd-44b8-863b-c611d325eac8)
