### ISSUE TITLE
Handle deprecation of inputs

### ISSUE THREAD

**Issue by fotoetienne** [apollographql/embeddable-explorer#267]
[Deprecation of input values](https://github.com/graphql/graphql-spec/pull/805) has now been merged into the GraphQL spec. This includes a [modification to the introspection query](https://github.com/graphql/graphql-spec/pull/805/files#r798845939). 

Without `includeDeprecated = true` on `inputFields` in the introspection query, an error occurs on any input objects that have all fields deprecated:
`Error: Invalid schema from introspection: Input Object type <typename> must define one or more fields.`

GraphiQL now has a flag that determines whether the introspection query should include `includeDeprecated = true` on `inputFields`, since only compatible graphs will know about this argument. Sandbox/explorer could do something similar or somehow autodetect whether the graph supports deprecation of input fields.

You just need to set the `inputValueDeprecation` arg in the graphql-js [getIntrospectionQuery](https://github.com/graphql/graphql-js/blob/main/src/utilities/getIntrospectionQuery.ts#L34) function.

**Comment by fotoetienne** [comment]
Digging in a bit, I see `inputValueDeprecation` included in `introspectionOptions` in `src/app/graph/explorerPage/hooks/useExplorerState/useSchema/useSchemaFromEndpointIntrospection/useSchemaFromEndpointIntrospection.ts` so maybe this just needs to be exposed or documented.

We are using the embedded sandbox in apollo-router and currently seeing the error described above.

**Comment by fotoetienne** [comment]
After more inspection, it seems that the introspection query does include deprecated on inputs. Nevertheless, there is an error in the console for an input type that has all fields deprecated
![Screen Shot 2023-07-21 at 6 02 22 PM](https://github.com/apollographql/embeddable-explorer/assets/693596/dc690591-8a09-44b1-b821-4ca03241c9ef)

**Comment by mayakoneval** [comment]
Hey! Apologies for the late reply here. 

This should be checking the introspection response to see if your `__Directive` type has `includeDeprecated` as an arg, and passing `includeDeprecated` to the introspection options when generating the query already.

I tested on a schema with a deprecated input field and am seeing it work alright: https://codesandbox.io/p/sandbox/as4-integration-testing-e90bft?file=%2Fsrc%2Fserver.ts%3A11%2C1-13%2C4

Would you be able to validate for me the version of graphql js you are using? 🙏🏻

**Comment by mayakoneval** [comment]
closing as we have not heard back
