### ISSUE TITLE
Enable Preflight Scripts in Sandbox Explorer

### ISSUE THREAD

**Issue by chriscerk** [apollographql/embeddable-explorer#271]
**Problem**

When using the Sandbox Embedded Explorer locally, 
after Authentication with Apollo Studio,
the Sandbox Embedded Explorer does not
have the preflight script functionality.

This causes friction for Apollo customers
who depend on preflight scripts for their
GraphQL requests.

**Context**

- Preflight scripts are a valuable feature for
  populating dynamic content in a GraphQL request
  such as user input, Authorization headers, etc.
- [A similar issue was submitted](https://github.com/apollographql/apollo-server/issues/7481) 
  but was closed due to lack of activity.

**Proposal**

When using the Sandbox Embedded Explorer locally,
after Authentication with Apollo Studio,
the Sandbox Embedded Explorer is able to
retrieve and invoke the preflight scripts
for their organization.

**Comment by mayakoneval** [comment]
Hello! Thanks for the report. 

I was able to run a preflight script from Sandbox after logging in. Just to verify, you are going to the settings tab on the left panel, then scrolling down to Preflight Script & editing / adding a preflight script, then you are flipping on the toggle under the Scripts section of the settings panel?

Would you be able to share a screen recording of the issue?
