### ISSUE TITLE
runTelemetry: false does not disable calls to m.stripe.com and others

### ISSUE THREAD

**Issue by aclarknexient** [apollographql/embeddable-explorer#285]
# Issue Description
When running an apollo non-prod landing page, disabling telemetry does not seem to work.

# Steps to Reproduce
1. Follow the **TypeScript** steps in https://www.apollographql.com/docs/apollo-server/getting-started up to the end of step 6.
2. Don't run the server yet.
3. Add the embed option to the ApolloServer plugins list
4. Add runTelemetry: false to the embed options. (Example is below)
5. Run `npm start` and open the server landing page at `http://localhost:4000/`
6. Open your browser's devtools network monitor and reload the landing page.
7. Observe calls to hosts outside the local network.

# Expected Behaviour
There should be no calls to external hosts:

# Actual Behaviour
Calls are made to the following hosts:
* events.launchdarkly.com
* clientstream.launchdarkly.com
* app.launchdarkly.com
* fonts.gstatic.com
* fonts.googleapis.com
* www.googletagmanager.com
* embeddable-sandbox.cdn.apollographql.com
* apollo-server-landing-page.cdn.apollographql.com
* sandbox.embed.apollographql.com
* studio-ui-deployments.apollographql.com/
* graphql.api.apollographql.com
* raw.githubusercontent.com
* sentry.io
* js.recurly.com
* js.stripe.com
* m.stripe.com
* m.stripe.network
[network-log.txt.zip](https://github.com/apollographql/embeddable-explorer/files/12872905/network-log.txt.zip)

```javascript
import { ApolloServer } from '@apollo/server';
import { startStandaloneServer } from '@apollo/server/standalone';
import { ApolloServerPluginLandingPageLocalDefault, ApolloServerPluginLandingPageProductionDefault } from '@apollo/server/plugin/landingPage/default';


// A schema is a collection of type definitions (hence "typeDefs")
// that together define the "shape" of queries that are executed against
// your data.
const typeDefs = `#graphql
  # Comments in GraphQL strings (such as this one) start with the hash (#) symbol.

  # This "Book" type defines the queryable fields for every book in our data source.
  type Book {
    title: String
    author: String
  }

  # The "Query" type is special: it lists all of the available queries that
  # clients can execute, along with the return type for each. In this
  # case, the "books" query returns an array of zero or more Books (defined above).
  type Query {
    books: [Book]
  }
`;

const books = [
  {
    title: 'The Awakening',
    author: 'Kate Chopin',
  },
  {
    title: 'City of Glass',
    author: 'Paul Auster',
  },
];

// Resolvers define how to fetch the types defined in your schema.
// This resolver retrieves books from the "books" array above.
const resolvers = {
  Query: {
    books: () => books,
  },
};

// The ApolloServer constructor requires two parameters: your schema
// definition and your set of resolvers.
const server = new ApolloServer({
  typeDefs,
  resolvers,
  plugins: [
    // Install a landing page plugin based on NODE_ENV
    process.env.NODE_ENV === 'production'
      ? ApolloServerPluginLandingPageProductionDefault({
          graphRef: 'my-graph-id@my-graph-variant',
          footer: false,
        })
      : ApolloServerPluginLandingPageLocalDefault({ 
        footer: false,
        embed: {
          runTelemetry: false,
        }
      }),
  ],
});

// Passing an ApolloServer instance to the `startStandaloneServer` function:
//  1. creates an Express app
//  2. installs your ApolloServer instance as middleware
//  3. prepares your app to handle incoming requests
const { url } = await startStandaloneServer(server, {
  listen: { port: 4000 },
});

console.log(`🚀  Server ready at: ${url}`);
```

**Comment by mayakoneval** [comment]
Hello! Thanks for the report.

The embedded Sandbox / Explorer is an iframe to our hosted site studio.apollographql.com. If you would like to use a non-hosted GraphiQL or bare bones landing page, we have [options for plugins in Apollo Server.](https://www.apollographql.com/docs/apollo-server/api/plugin/landing-pages/#graphql-playground-landing-page) 

The team is working on minimizing the amount of network calls you listed here for folks who request `runTelemetry: false`. Note that many of these calls are not telemetry: stripe & recurly are for billing, launchdarkly is our feature flag service, all the apollographql.com calls are to our cdn which hosts the favicon or the bundle you are seeing. The Google telemetry calls you do see are script calls that we don't act on if you have run `runTelemetry: false`, but we are working on not making the set up calls to begin with. 

I'll update when any changes have been shipped, thanks!

**Comment by mayakoneval** [comment]
Hi! we shipped a fix so you shouldn't see telemetry initial calls at all now. Thanks!

**Comment by advance512** [comment]
Unfortunately we still see this happening with apollo/server v4.12.0.

![Image](https://github.com/user-attachments/assets/6b6abc11-92bd-44b8-863b-c611d325eac8)
