### ISSUE TITLE
Graphql Subscription connectionParams

### ISSUE THREAD

**Issue by georgesofianosgr** [apollographql/embeddable-explorer#289]
Reading the [documentation](https://www.apollographql.com/docs/graphos/explorer/subscriptions-explorer) I cannot find a way to pass connectionParams in subscriptions.

We use connectionParams for authorization. 
Did I miss something or there is no way to pass connectionParams ?

**Comment by mayakoneval** [comment]
Hi! Apologies for the delay in response. Are you looking to pass headers? If you are - you can do that with the `headers` [option](https://www.apollographql.com/docs/graphos/explorer/embed-explorer/#headers). 

If you are looking to set these on an Embedded Explorer, you can do that from the shared headers in the connection settings on your graph as well.

**Comment by vindard** [comment]
Same question, when I open `Connection Setting` these aren't editable. I'd like to somehow be able to configure that `Subscription Endpoint` string

![image](https://github.com/apollographql/embeddable-explorer/assets/17693119/c37d2648-732d-46c4-b04c-d62d0eb70cde)

**Comment by mayakoneval** [comment]
Hi - you can pass `initialSubscriptionEndpoint` to your `EmbeddedSandbox` instance to configure the subscription endpoint, thank you!
