### ISSUE TITLE
Endpoint query parameter not being added to the sandbox textbox

### ISSUE THREAD

**Issue by Alfonso2104** [apollographql/embeddable-explorer#295]
The sandbox textbox stopped getting the url from the endpoint query parameter instead it is setting the full browser url.
![image](https://github.com/apollographql/embeddable-explorer/assets/62553780/20fb64b8-6c9e-4c7b-91f8-d0969853b015)

I am using apollo version 4

**Comment by mayakoneval** [comment]
Hi! We did this on purpose due to security concerns for bad actors providing links with unexpected endpoints. Thank you 🙏🏻
