### ISSUE TITLE
subscriptions-transport-ws package is no longer maintained

### ISSUE THREAD

**Issue by forivall** [apollographql/embeddable-explorer#296]
When I install `@apollo/sandbox`, I see the following warning from `npm`:

`
subscriptions-transport-ws@0.11.0: The ``subscriptions-transport-ws`` package is no longer maintained. We recommend you use ``graphql-ws`` instead. For help migrating Apollo software to ``graphql-ws``, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using ``graphql-ws``, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
`

I suppose this is to support old versions of apollo server that still use the old subscriptions ws transport, but it's worth recording this in an issue even if this is `wontfix`

**Comment by mayakoneval** [comment]
yes thank you! it is a wontfix for the reason you mentioned
