### ISSUE TITLE
The mock server response option is not working

### ISSUE THREAD

**Issue by happydroid** [apollographql/embeddable-explorer#45]
I have embedded your snippet of code from the documentation in my web application. The embedded section works fine, but the server response mock option does not work (does not apply):
![image](https://user-images.githubusercontent.com/2048603/160705017-d9961fae-6f3d-47aa-9114-21cd270886e2.png)

Tell me please if it is possible to add support for this option or I have understood something wrong and this option works ?

**Comment by mayakoneval** [comment]
Hello! Thanks for reporting. 

Are you turning on mocking in a separate, non-embedded, tab and then coming back to the Embedded Explorer and expecting to see mocked responses? If so, we don't support mocked responses in the embed right now, but I don't see why we shouldn't. I can make a ticket to support this in the future. 

Let me know if you have any other questions. 

Maya

**Comment by happydroid** [comment]
Hello Maya, thanks for the quick response. 

>Are you turning on mocking in a separate, non-embedded, tab and then coming back to the Embedded Explorer and expecting to see mocked responses?

Yes, I started connecting your embedded explorer to angular app as a task at my job. I clarified, I need to call a real server and get real data, which I already did, your explorer works fine =)

But maybe the option to get mock response data for the embedded explorer would make sense in the future for other users. For example, in the case when you want to give users the opportunity to test the graphql api without changing the production data or if users hasn't permissions to manipulate production data.

At the moment I have no more questions, thanks for the answer.

Artyom

**Comment by mayakoneval** [comment]
Hi @happydroid, we have released the ability to turn on mock responses for the embedded explorer recently. Now, when you visit your embedded explorer, you should see the settings tab available. In that tab, you can turn on mock responses. 

Let me know if that works for you!
Maya
